spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security
    username: root
    password: 29092003
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

#logging:
#  level:
#    root: warn
#    org.hibernate.SQL: trace
#    org.hibernate.orm.jdbc.bind: trace
#

